M48
; DRILL file {KiCad (6.0.0)} date Thu Dec 30 12:50:36 2021
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2021-12-30T12:50:36-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0941
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1358
%
G90
G05
T1
X4.4567Y-5.561
X4.6535Y-5.561
T2
X5.8632Y-5.6744
X5.9813Y-5.6744
T3
X3.3841Y-4.8179
T4
X3.7077Y-4.188
X5.8809Y-4.8179
T0
M30
